spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/DisplayU
    username: DisplayUser
    password: "displayu2026!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  kakao:
    client:
      id: ${KAKAO_CLIENT_ID}
  google:
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}

jjwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
  signup-expiration: ${JWT_SIGNUP_EXPIRATION:600000}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    doc-expansion: list
    display-request-duration: true