spring:
  application:
    name: demo

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  display:
    invitation:
      base-url: https://displayu.co.kr/display/invitation
  kakao:
    client:
      id: test-kakao-client-id
      secret:
    redirect-uri: http://localhost:8080/api/auth/kakao/callback
  google:
    client:
      id: test-google-client-id
      secret: test-google-client-secret
    redirect-uri: http://localhost:8080/api/auth/google/callback
  oauth:
    cookie-secure: false
