spring:
  application:
    name: demo

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  display:
    invitation:
      base-url: https://displayu.co.kr/display/invitation
  kakao:
    client:
      id: test-kakao-client-id
  google:
    client:
      id: test-google-client-id
