CREATE TABLE `PersonalArtwork` (
    `personalArtworkId` BIGINT NOT NULL AUTO_INCREMENT,
    `artworkName` VARCHAR(255) NOT NULL,
    `content` TEXT NULL,
    `type` ENUM('PAINTING', 'DESIGN', 'PHOTOGRAPHY', 'ARCHITECTURE', 'VIDEO', 'CRAFTS', 'SCULPTURE', 'FASHION', 'ILLUSTRATION', 'OTHERS') NOT NULL COMMENT 'PAINTING, DESIGN, PHOTOGRAPHY, ARCHITECTURE, VIDEO, CRAFTS, SCULPTURE, FASHION, ILLUSTRATION, OTHERS',
    `productionYear` INT NOT NULL,
    `materialMedia` VARCHAR(255) NOT NULL,
    `size` VARCHAR(255) NULL,
    `point` TEXT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deletedAt` DATETIME NULL,
    `userId` BIGINT NOT NULL,
    CONSTRAINT `PK_PERSONALARTWORK` PRIMARY KEY (`personalArtworkId`)
);

CREATE TABLE `PersonalArtworkImage` (
    `personalArtworkImageId` BIGINT NOT NULL AUTO_INCREMENT,
    `imageUrl` TEXT NOT NULL,
    `isThumbnail` BOOLEAN NOT NULL DEFAULT FALSE,
    `imageType` ENUM('ARTWORK', 'WORK_PROCESS') NOT NULL DEFAULT 'ARTWORK' COMMENT 'ARTWORK, WORK_PROCESS',
    `sortOrder` INT NOT NULL,
    `caption` VARCHAR(255) NULL,
    `width` INT NOT NULL,
    `height` INT NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deletedAt` DATETIME NULL,
    `personalArtworkId` BIGINT NOT NULL,
    CONSTRAINT `PK_PERSONALARTWORKIMAGE` PRIMARY KEY (`personalArtworkImageId`)
);

ALTER TABLE `PersonalArtwork`
    ADD CONSTRAINT `FK_PERSONALARTWORK_USER` FOREIGN KEY (`userId`) REFERENCES `User` (`userId`);

ALTER TABLE `PersonalArtworkImage`
    ADD CONSTRAINT `FK_PERSONALARTWORKIMAGE_PERSONALARTWORK` FOREIGN KEY (`personalArtworkId`) REFERENCES `PersonalArtwork` (`personalArtworkId`);
