ALTER TABLE `ArchiveDisplay` ADD CONSTRAINT `FK_ARCHIVEDISPLAY_DISPLAY` FOREIGN KEY (`displayId`) REFERENCES `Display` (`displayId`);
ALTER TABLE `ArchiveDisplay` ADD CONSTRAINT `FK_ARCHIVEDISPLAY_USER` FOREIGN KEY (`userId`) REFERENCES `User` (`userId`);

ALTER TABLE `ArchiveWork` ADD CONSTRAINT `FK_ARCHIVEWORK_DISPLAYARTWORK` FOREIGN KEY (`displayArtworkId`) REFERENCES `DisplayArtwork` (`displayArtworkId`);
ALTER TABLE `ArchiveWork` ADD CONSTRAINT `FK_ARCHIVEWORK_USER` FOREIGN KEY (`userId`) REFERENCES `User` (`userId`);

ALTER TABLE `ArchiveArtist` ADD CONSTRAINT `FK_ARCHIVEARTIST_USER` FOREIGN KEY (`userId`) REFERENCES `User` (`userId`);
ALTER TABLE `ArchiveArtist` ADD CONSTRAINT `FK_ARCHIVEARTIST_CREATOR` FOREIGN KEY (`creatorId`) REFERENCES `Creator` (`creatorId`);

ALTER TABLE `Memo` ADD CONSTRAINT `FK_MEMO_ARCHIVEDISPLAY` FOREIGN KEY (`archiveDisplayId`) REFERENCES `ArchiveDisplay` (`archiveDisplayId`);
ALTER TABLE `Memo` ADD CONSTRAINT `FK_MEMO_ARCHIVEWORK` FOREIGN KEY (`archiveWorkId`) REFERENCES `ArchiveWork` (`archiveWorkId`);
    