CREATE TABLE `ArtistProfile` (
    `artistProfileId` BIGINT NOT NULL AUTO_INCREMENT,
    `userId` BIGINT NOT NULL,
    `artistName` VARCHAR(50) NOT NULL,
    `schoolEmail` VARCHAR(255) NOT NULL,
    `univName` VARCHAR(255) NOT NULL,
    `portfolioUrl` VARCHAR(255) NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`artistProfileId`),
    CONSTRAINT `UK_ARTISTPROFILE_USER` UNIQUE (`userId`),
    CONSTRAINT `UK_ARTISTPROFILE_ARTIST_NAME` UNIQUE (`artistName`),
    CONSTRAINT `FK_ARTISTPROFILE_USER` FOREIGN KEY (`userId`) REFERENCES `User` (`userId`)
);

CREATE TABLE `AreaOfActivity` (
    `areaOfActivityId` BIGINT NOT NULL AUTO_INCREMENT,
    `artistProfileId` BIGINT NOT NULL,
    `field` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`areaOfActivityId`),
    CONSTRAINT `UK_AREA_OF_ACTIVITY_PROFILE_FIELD` UNIQUE (`artistProfileId`, `field`),
    CONSTRAINT `FK_AREA_OF_ACTIVITY_ARTIST_PROFILE`
        FOREIGN KEY (`artistProfileId`) REFERENCES `ArtistProfile` (`artistProfileId`)
);
