ALTER TABLE `DisplayLike`
    CHANGE COLUMN `dislikeId` `displayLikeId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayLike`
    ADD COLUMN `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `createdAt`,
    ADD COLUMN `deletedAt` DATETIME NULL AFTER `updatedAt`;

ALTER TABLE `DisplayLike`
    ADD CONSTRAINT `UQ_DISPLAYLIKE_DISPLAY_USER` UNIQUE (`displayId`, `userId`);

ALTER TABLE `DisplayLike`
    ADD CONSTRAINT `FK_DISPLAYLIKE_DISPLAY` FOREIGN KEY (`displayId`) REFERENCES `Display` (`displayId`);
