ALTER TABLE DisplayReview
    ADD COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN deletedAt DATETIME NULL,
    ADD CONSTRAINT UQ_DISPLAY_REVIEW_DISPLAY_USER UNIQUE (displayId, userId);

ALTER TABLE DisplayReviewImage
    ADD COLUMN createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN sortOrder INT NOT NULL DEFAULT 0,
    ADD CONSTRAINT FK_DISPLAY_REVIEW_IMAGE_REVIEW
        FOREIGN KEY (displayReviewId) REFERENCES DisplayReview (displayReviewId);

CREATE INDEX IDX_DISPLAY_REVIEW_CURSOR
    ON DisplayReview (displayId, deletedAt, displayReviewId);
