ALTER TABLE `DisplayContentCategory`
    MODIFY COLUMN `categoryId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `Agreement`
    MODIFY COLUMN `agreeId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayContent`
    MODIFY COLUMN `displayContentId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TeamMember`
    MODIFY COLUMN `teamId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `LoungePost`
    MODIFY COLUMN `loungePostId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkFeelingReply`
    MODIFY COLUMN `feelingReplyId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArchiveArtist`
    MODIFY COLUMN `archiveArtistId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArchiveDisplay`
    MODIFY COLUMN `archiveDisplayId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkQuestionReply`
    MODIFY COLUMN `queReplyId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayReviewImage`
    MODIFY COLUMN `reviewImageId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `RefreshToken`
    MODIFY COLUMN `tokenId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `MemoImage`
    MODIFY COLUMN `memoImageId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayInvitation`
    MODIFY COLUMN `disInvitationId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArchiveWork`
    MODIFY COLUMN `archiveWorkId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkFeelingLike`
    MODIFY COLUMN `areLikeId` BIGINT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN `feelingId` BIGINT NOT NULL;

ALTER TABLE `DisplayLike`
    MODIFY COLUMN `dislikeId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayArtwork`
    MODIFY COLUMN `displayArtworkId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkImage`
    MODIFY COLUMN `artImageId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `LoungePostLike`
    MODIFY COLUMN `loungePostLikeId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `Creator`
    MODIFY COLUMN `creatorId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `UserAgreement`
    MODIFY COLUMN `userAgreeId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkQuestion`
    MODIFY COLUMN `artQueId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `Display`
    MODIFY COLUMN `displayId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `Column`
    MODIFY COLUMN `columnId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `ArtworkFeeling`
    MODIFY COLUMN `feelingId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `Memo`
    MODIFY COLUMN `memoId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `User`
    MODIFY COLUMN `userId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayReview`
    MODIFY COLUMN `displayReviewId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `DisplayImage`
    MODIFY COLUMN `disImageId` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `LoungeComment`
    MODIFY COLUMN `loungeCommentId` BIGINT NOT NULL AUTO_INCREMENT;
