ALTER TABLE `LoungePost`
    ADD COLUMN `postImageUrl` TEXT NULL AFTER `title`;

ALTER TABLE `LoungePost`
    MODIFY COLUMN `category` ENUM('DISPLAY_REVIEW', 'WORK_TIP', 'COLLABORATION', 'SPACE_RENTAL') NOT NULL COMMENT 'DISPLAY_REVIEW, WORK_TIP, COLLABORATION, SPACE_RENTAL';

ALTER TABLE `LoungeComment`
    ADD COLUMN `parentCommentId` BIGINT NULL AFTER `deletedAt`;

CREATE TABLE `LoungeCommentLike` (
    `loungeCommentLikeId` BIGINT NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `loungeCommentId` BIGINT NOT NULL,
    `userId` BIGINT NOT NULL,
    CONSTRAINT `PK_LOUNGECOMMENTLIKE` PRIMARY KEY (`loungeCommentLikeId`)
);

ALTER TABLE `LoungePostLike`
    ADD CONSTRAINT `UK_LOUNGEPOSTLIKE_POST_USER` UNIQUE (`loungePostId`, `userId`);

ALTER TABLE `LoungeCommentLike`
    ADD CONSTRAINT `UK_LOUNGECOMMENTLIKE_COMMENT_USER` UNIQUE (`loungeCommentId`, `userId`);
