ALTER TABLE `ArchiveDisplay` ADD COLUMN `savedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ArchiveWork` ADD COLUMN `savedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ArchiveArtist` ADD COLUMN `savedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
